In [32]:
import numpy as np

## Q1

In [33]:
x = np.arange(1, 20.1, 0.1)

In [34]:
y = []

In [35]:
for i in x:
    y.append(3*i + 2 + np.random.randn())

In [36]:
y = np.array(y)

In [37]:
X = np.c_[np.ones(len(x)), x] 
y = y.reshape(-1,1)

In [38]:
print(X.shape)
print(y.shape)

(191, 2)
(191, 1)


### Normal equations

In [39]:
theta = np.linalg.inv(X.T @ X) @ (X.T @ y)

In [40]:
theta

array([[2.14311608],
       [2.99763416]])

### Batch gradient descent

In [41]:
terminal = False
alpha = 0.01
i = 0
w_t = np.random.randn(2).reshape(-1,1)

print(w_t.shape)

(2, 1)


In [42]:
n = X.shape[0]
while not terminal:

    y_pred = X @ w_t
    loss = (1 / (2 * n)) * np.sum((y - y_pred)**2)
    
    gradient = (1/n) * X.T @ (X @ w_t - y)
    w_t = w_t - (alpha)*gradient

    #print(f"Loss: {loss}")
    
    if np.linalg.norm(gradient) < 1e-06:
        terminal = True

In [43]:
w_t

array([[2.14311146],
       [2.9976345 ]])

### Stochastic Gradient Descent

In [44]:
terminal = False
alpha = 0.01
i = 0
w_t = np.random.randn(2).reshape(-1,1)

while not terminal:

    row = np.random.randint(0, X.shape[0])

    loss = 0.5 * (y[row] - y_pred[row])**2
    gradient = X[row].T.reshape(2,1) @ (X[row].reshape(1, 2) @ w_t.reshape(-1, 1) - y[row].reshape(1, 1))
    w_t = w_t - alpha*gradient

    #print(f"Loss: {loss}")
    
    i = i + 1
    alpha = alpha * 0.999
    
    if i > 100000:
        terminal = True

In [45]:
w_t

array([[1.89309337],
       [3.01620622]])

### Mini Batch Gradient Descent

In [46]:
def generate_batches(mini_batch_size=32):

    j = 0
    mini_batches = []
    
    while j < mini_batch_size:
        row = np.random.randint(0, X.shape[0])
        if row not in mini_batches:
            mini_batches.append(row)
            j = j + 1
    
    mini_batches.sort()

    h = []
    for i in mini_batches:
        h.append(X[i])

    X_mbgd = np.vstack(tuple(h))

    h = []
    for i in mini_batches:
        h.append(y[i])
    
    y_mbgd = np.vstack(tuple(h))

    return X_mbgd, y_mbgd

In [47]:
terminal = False
alpha = 0.01
i = 0
w_t = np.random.randn(2).reshape(-1,1)

while not terminal:


    X_mbgd, y_mbgd = generate_batches()
    n = X_mbgd.shape[0]

    loss = (1 / (2 * n)) * np.sum((X_mbgd @ w_t - y_mbgd)**2)

    #print(f"Loss: {loss}")
    
    gradient = (1/n) * X_mbgd.T @ (X_mbgd @ w_t - y_mbgd)
    w_t = w_t - (alpha)*gradient
    i = i + 1
    
    if np.linalg.norm(gradient) < 1e-06 or i > 100000:
        terminal = True

In [48]:
w_t

array([[2.15661085],
       [2.99981728]])