# Reinforcement Learning
## Formative Assessment: Value Iteration
In this formative exercise, you will implement the Value Iteration algorithm to compute an optimal policy for three different (but closely related) Markov Decision Processes. For your reference, the pseudo-code for the Value Iteration algorithm is reproduced below from the textbook (Reinforcement Learning, Sutton & Barto, 2018, pp. 83).

<img src="images/value_iteration.png" style="width: 800px;"/>

Please note the following about the pseudo-code: The set $\mathcal{S}$ contains all non-terminal states, whereas $\mathcal{S}^+$ is the set of all states (terminal and non-terminal). The symbol $r$ represents the immediate reward on transition from state $s$ to the next state $s'$ via action $a$. 

<img src="images/bombs and gold numbers.png" style="width: 320px;" align="left" caption="Figure 1"/>

The two problems you will solve use variants of the gridworld environment shown on the left. You should be familiar with this kind of environment from the content you have seen so far in this unit. The grid squares in the figure are numbered as shown. In all exercises, the following are true: 

**Actions available:** The agent has four possible actions in each grid square. These are *west*, *north*, *south*, and *east*. If the direction of movement is blocked by a wall (for example, if the agent executes action south in grid square 1), the agent remains in the same grid square. 

**Collecting gold:** On its first arrival at a grid square that contains gold (from a neighbouring grid square), the agent collects the gold. Note that, in order to collect the gold, the agent needs to transition into the grid square (containing the gold) from a different grid square.

**Hitting the bomb:** On arrival at a grid square that contains a bomb (from a neighbouring grid square), the agent activates the bomb. 

**Terminal states:** The game terminates when **all** gold is collected or when the bomb is activated. In Exercises 1 and 2, you can define terminal states to be grid squares 18 and 23. In Exercise 3, you will need to define terminal state(s) differently.


### Instructions ###
Set parameter $\theta$ to $1 \times 10 ^{-10}$. You can express that as `1e-10` in Python. 

Set all initial state values $V(s)$ to zero.

Do not use discounting (that is, set $\gamma=1$).

Use the following reward function: $-1$ for each navigation action (including when the action results in hitting the wall), an additional $+10$ for collecting each piece of gold, and an additional $-10$ for activating the bomb. For example, the immediate reward for transitioning into a square with gold (from a neighbouring grid square) is $-1 + 10 = +9$. 

## Exercise 1: Deterministic Environment (0 Marks)

In this exercise, the agent is able to move in the intended direction with certainty. For example, if it executes action _north_ in grid square 0, it will transition to grid square 5 with probability 1. In other words, we have a deterministic environment.

Compute the optimal policy using Value Iteration. 

Your need to produce two one-dimensional numpy arrays with names `policy` and `v`. Both arrays should have a length of 25, with the element at index $i$ representing grid cell $i$ (see figure above). Both arrays should be accessible in the "solution cell" below!

The array `policy` should be a numpy array of strings that specifies an optimal action at each grid location. Please use the abbreviations `"n"`, `"e"`, `"s"`, and `"w"` for the four actions. As an example, the value of `policy` at index `0` needs to give `"n"`, if _north_ is an optimal action in cell 0. The policy for a terminal state can be any action. If there are multiple optimal actions from a state, any optimal action will be considered as a correct answer. 

The array `v` should be an array of floats that contains the expected return at each grid square (that is, the state value under the optimal policy).

In [33]:
# Please write your code for Exercise 1 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm.

# YOUR CODE HERE

In [32]:
import numpy as np

bomb_positions = np.array([18])
gold_positions = np.array([23])
rewards = np.zeros(25)
v = np.zeros(25)
policy = np.empty(25, dtype='<U1')

theta = 1e-10
gamma = 1

rewards[18] = -10
rewards[23] = 10

In [26]:
def make_step(agent_position, action):

    old_position = agent_position
    new_position = agent_position
    num_cols = 5
    num_cells = 25
    
    
    if action == "n":
        candidate_position = old_position + num_cols
        if candidate_position < num_cells:
            new_position = candidate_position
    elif action == "e":
        candidate_position = old_position + 1
        if candidate_position % num_cols > 0:  # The %-op
            new_position = candidate_position
    elif action == "s":
        candidate_position = old_position - num_cols
        if candidate_position >= 0:
            new_position = candidate_position
    elif action == "w":  # "LEFT"
        candidate_position = old_position - 1
        if candidate_position % num_cols < num_cols - 1:
            new_position = candidate_position
        
    agent_position = new_position
        
        # Calculate reward
    reward = rewards[agent_position]
    reward = -1 + rewards[new_position]
    return reward, new_position

In [27]:
while True:
    
    delta = 0
    v_new = np.copy(v)
    
    for i in range(0, 25):

        if i in [18, 23]:
            continue
        
        this_v = v[i]
        q_values = []

        for action in ['n', 'e', 's', 'w']:
            reward, new_pos = make_step(i, action)
            q_values.append(reward + gamma*v[new_pos])
            
        v_new[i] = max(q_values)
        delta = max(delta, abs(v_new[i] - this_v))

    v = v_new
        
    if delta < theta:
        break

In [31]:
for i in range(0, 25):
    if i in [18, 23]:
        policy[i] = 'n'
        continue

    q_values = {}
    for action in ['n', 'e', 's', 'w']:
        r, new_pos = make_step(i, action)
        q_values[action] = r + gamma * v[new_pos]

    best_action = max(q_values, key=q_values.get)
    policy[i] = best_action


**Example Test Cell**

In the code cell below, we have provided an example of the type of test code that we will use to mark your work. In these tests, we first check that your `policy` and `v` variables are of the correct type, and then check that their values match the solution. For the remaining exercises, the answers will be hidden from you until the model answers are released.

In [5]:
# DO NOT DELETE OR MODIFY THIS CELL!
# Your code for Exercise 1 is tested here.

import numpy as np

# We're giving you the solution values for Exercise 1, but not telling you how to compute them!
solution_values = [3.0, 4.0, 5.0, 4.0, 5.0,
                   4.0, 5.0, 6.0, 5.0, 6.0,
                   5.0, 6.0, 7.0, 6.0, 7.0,
                   6.0, 7.0, 8.0, 0.0, 8.0,
                   7.0, 8.0, 9.0, 0.0, 9.0]
solution_values = np.array(solution_values)

# We're giving you the solution policy for Exercise 1, but not telling you how to compute it!
solution_policy = [
                   'n', 'n', 'n', 'n', 'n',
                   'n', 'n', 'n', 'n', 'n',
                   'n', 'n', 'n', 'e', 'n',
                   'n', 'n', 'n', 'n', 'n',
                   'e', 'e', 'e', 'n', 'w',]
solution_policy = np.array(solution_policy)

# Check that policy and v are numpy arrays.
assert(isinstance(policy, np.ndarray))
assert(isinstance(v, np.ndarray))

# Check correct shapes of numpy arrays.
assert(policy.shape == (25, ))
assert(v.shape == (25, ))

# Check whether the numpy arrays have the correct data types.
assert(np.issubdtype(policy.dtype, np.str_)) # policy.dtype should be '<U1'
assert(np.issubdtype(v.dtype, np.float64))

# Check whether policy contains only "n", "w", "s", or "e" values.
assert(np.all(np.isin(policy, np.array(["n", "w", "s", "e"]))))

# Print student's solution and true solution for easier comparison / spotting of errors.
print("Student's policy:")
print(np.flip(policy.reshape((5, 5)), 0))
print("Solution policy:")
print(np.flip(solution_policy.reshape((5, 5)), 0))
print("\n")
print("Student's v:")
print(np.flip(v.reshape((5, 5)), 0))
print("Solution v:")
print(np.flip(solution_values.reshape((5, 5)), 0))

# Compare state values for non-terminal states.
states_to_check = np.delete(np.arange(25), np.array([18, 23]))
incorrect_error_message = "[Marking Advice] State values incorrect."
np.testing.assert_array_almost_equal(v[states_to_check], solution_values[states_to_check], decimal=3, err_msg=incorrect_error_message)

# Compare policy (only on states that have a single optimal direction).
states_to_check =  np.array([4, 9, 14, 17, 19, 20, 22, 24])
incorrect_error_message = "[Marking Advice] Policy incorrect."
np.testing.assert_array_equal(policy[states_to_check], solution_policy[states_to_check], err_msg=incorrect_error_message)

# Compare state values for terminal states.
states_to_check =  np.array([18, 23])
incorrect_error_message = "[Marking Advice] Value of terminal state is not zero."
np.testing.assert_array_equal(v[states_to_check], solution_values[states_to_check], err_msg=incorrect_error_message)

Student's policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]
Solution policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'n' 'n']]


Student's v:
[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]
Solution v:
[[7. 8. 9. 0. 9.]
 [6. 7. 8. 0. 8.]
 [5. 6. 7. 6. 7.]
 [4. 5. 6. 5. 6.]
 [3. 4. 5. 4. 5.]]


## Exercise 2: Stochastic Environment

In this exercise, we introduce stochasticity into the environment. Now, the agent is not always able to execute its actions as intended.

With probability 0.8, the agent moves as intended. However, with probability 0.2, it moves in a random direction.

For example, from grid square 0, if the agent tries to move north, with probability 0.8 the action will work as intended. But with probability 0.2, the agent's motor control system will move it in a random direction (including north). So, it will randomly try to move west, east, north or south with probability 0.05 each. Notice that the total probability of moving to square 5 (as intended) is 0.8 + 0.05 = 0.85.
 
Compute the optimal policy using Value Iteration.

Your value iteration method should output two one-dimensional numpy arrays with names `policy` and `v`, as in Exercise 1.

In [49]:
# Please write your code for Exercise 2 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm.

# YOUR CODE HERE

import numpy as np

bomb_positions = np.array([18])
gold_positions = np.array([23])
rewards = np.zeros(25)
v = np.zeros(25)
policy = np.empty(25, dtype='<U1')

theta = 1e-10
gamma = 1

rewards[18] = -10
rewards[23] = 10

In [50]:
def make_step(agent_position, action):

    old_position = agent_position
    new_position = agent_position
    num_cols = 5
    num_cells = 25
    
    
    if action == "n":
        candidate_position = old_position + num_cols
        if candidate_position < num_cells:
            new_position = candidate_position
    elif action == "e":
        candidate_position = old_position + 1
        if candidate_position % num_cols > 0:  # The %-op
            new_position = candidate_position
    elif action == "s":
        candidate_position = old_position - num_cols
        if candidate_position >= 0:
            new_position = candidate_position
    elif action == "w":  # "LEFT"
        candidate_position = old_position - 1
        if candidate_position % num_cols < num_cols - 1:
            new_position = candidate_position
        
    agent_position = new_position
        
        # Calculate reward
    reward = -1 + rewards[new_position]
    return reward, new_position

In [51]:
while True:
    
    delta = 0
    v_new = np.copy(v)
    
    for i in range(0, 25):

        if i in [18, 23]:
            continue
        
        this_v = v[i]
        q_values = []

        for action in ['n', 'e', 's', 'w']:
            exp_value = 0
            for actual_action in ['n', 'e', 's', 'w']:
                if action == actual_action:
                    prob = 0.85
                else:
                    prob = 0.05
                reward, new_pos = make_step(i, actual_action)
                exp_value = exp_value + prob*(reward + gamma*v[new_pos])
            q_values.append(exp_value)
            
        v_new[i] = max(q_values)
        delta = max(delta, abs(v_new[i] - this_v))

    v = v_new
        
    if delta < theta:
        break

In [53]:
for i in range(0, 25):
    if i in [18, 23]:
        policy[i] = 'n'
        continue

    q_values = {}
    for action in ['n', 'e', 's', 'w']:
        exp_value = 0
        for actual_action in ['n', 'e', 's', 'w']:
            if action == actual_action:
                prob = 0.85
            else:
                prob = 0.05
            reward, new_pos = make_step(i, actual_action)
            exp_value = exp_value + prob*(reward + gamma*v[new_pos])
        q_values[action] = exp_value

    best_action = max(q_values, key=q_values.get)
    policy[i] = best_action


In [54]:
# DO NOT DELETE OR MODIFY THIS CELL!

print("Student's v:")
print(np.flip(v.reshape((5, 5)), 0))
print("\n")
print("Student's policy:")
print(np.flip(policy.reshape((5, 5)), 0))

Student's v:
[[6.04169329 7.28756636 8.61359951 0.         8.69262311]
 [4.86185111 5.99087587 6.37082431 0.         6.46721593]
 [3.67550938 4.69621388 4.99441863 3.2189158  5.10250988]
 [2.48699534 3.40945989 3.66922967 2.64122933 3.78610115]
 [1.35979208 2.19733672 2.42878751 1.57272161 2.55202451]]


Student's policy:
[['e' 'e' 'e' 'n' 'w']
 ['n' 'n' 'n' 'n' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'e' 'n']
 ['n' 'n' 'n' 'n' 'n']]


## Exercise 3: Stochastic Environment with Two Pieces of Gold (6 Marks)

<img src="images/bomb and two gold.png" style="width: 300px;" align="left" caption="Figure 1"/> In this exercise, we have modified the environment presented in exercise 2. A second piece of gold has been placed on grid square 12, and a terminal state is reached only when **both** pieces of gold have been collected, or when the bomb is activated.

Compute the optimal policy for this altered environment using Value Iteration.

Your method should output two one-dimensional numpy arrays with names `policy` and `v`, as in the previous exercises. Each value in these arrays should specify the expected return and optimal policy at the corresponding grid sqaure **before any pieces of gold are collected or a bomb is activated.** 

Hint: You will need to change your state representation in order to account for the additional piece of gold.

In [58]:
# Please write your code for Exercise 3 in this cell or in as many cells as you want ABOVE this cell.
# Your code should compute the values of policy and v from scratch when this cell is executed, 
# using the value iteration algorithm.

# YOUR CODE HERE

import numpy as np

bomb_positions = np.array([18])
gold_positions = np.array([12, 23])
rewards = np.zeros(25)
v = np.zeros(25)
policy = np.empty(25, dtype='<U1')

theta = 1e-10
gamma = 1

rewards[12] = 10
rewards[18] = -10
rewards[23] = 10

In [59]:
def make_step(agent_position, action):

    old_position = agent_position
    new_position = agent_position
    num_cols = 5
    num_cells = 25
    
    
    if action == "n":
        candidate_position = old_position + num_cols
        if candidate_position < num_cells:
            new_position = candidate_position
    elif action == "e":
        candidate_position = old_position + 1
        if candidate_position % num_cols > 0:  # The %-op
            new_position = candidate_position
    elif action == "s":
        candidate_position = old_position - num_cols
        if candidate_position >= 0:
            new_position = candidate_position
    elif action == "w":  # "LEFT"
        candidate_position = old_position - 1
        if candidate_position % num_cols < num_cols - 1:
            new_position = candidate_position
        
    agent_position = new_position
        
        # Calculate reward
    reward = -1 + rewards[new_position]
    return reward, new_position

In [60]:
while True:
    
    delta = 0
    v_new = np.copy(v)
    
    for i in range(0, 25):

        if i in [12, 18, 23]:
            continue
        
        this_v = v[i]
        q_values = []

        for action in ['n', 'e', 's', 'w']:
            exp_value = 0
            for actual_action in ['n', 'e', 's', 'w']:
                if action == actual_action:
                    prob = 0.85
                else:
                    prob = 0.05
                reward, new_pos = make_step(i, actual_action)
                exp_value = exp_value + prob*(reward + gamma*v[new_pos])
            q_values.append(exp_value)
            
        v_new[i] = max(q_values)
        delta = max(delta, abs(v_new[i] - this_v))

    v = v_new
        
    if delta < theta:
        break

In [61]:
for i in range(0, 25):
    if i in [12, 18, 23]:
        policy[i] = 'n'
        continue

    q_values = {}
    for action in ['n', 'e', 's', 'w']:
        exp_value = 0
        for actual_action in ['n', 'e', 's', 'w']:
            if action == actual_action:
                prob = 0.85
            else:
                prob = 0.05
            reward, new_pos = make_step(i, actual_action)
            exp_value = exp_value + prob*(reward + gamma*v[new_pos])
        q_values[action] = exp_value

    best_action = max(q_values, key=q_values.get)
    policy[i] = best_action


In [62]:
# DO NOT DELETE OR MODIFY THIS CELL!

print("Student's v:")
print(np.flip(v.reshape((5, 5)), 0))
print("\n")
print("Student's policy:")
print(np.flip(policy.reshape((5, 5)), 0))

Student's v:
[[6.27185527 7.4483022  8.69750488 0.         8.69690012]
 [6.27225747 7.38830369 7.80429043 0.         6.5442022 ]
 [7.29987383 8.60242493 0.         7.68979128 6.49253977]
 [6.18412144 7.36032106 8.59757988 7.30328591 6.08760162]
 [5.07297558 6.18349601 7.2879906  6.12946745 5.01603046]]


Student's policy:
[['e' 'e' 'e' 'n' 'w']
 ['e' 's' 's' 'n' 'n']
 ['e' 'e' 'n' 'w' 'w']
 ['e' 'n' 'n' 'w' 'w']
 ['n' 'n' 'n' 'n' 'w']]
