
# Operational Software Technologies

## NumPy Broadcasting Worksheet Solutions

This notebook contains the **completed solutions** to the broadcasting worksheet.  

Dr Moody Alam

## Topics

>[Exercise 1 — Scalar Broadcasting (Solution)](#scrollTo=dcc2ff2f)

>[Exercise 2 — Matrix + Vector Broadcasting (Solution)](#scrollTo=c535e9d1)

>[Exercise 3 — Row + Column Broadcasting (Solution)](#scrollTo=2d629bc4)

>[Exercise 4 — Broadcasting Error (Solution)](#scrollTo=a335217d)

## Exercise 1 — Scalar Broadcasting (Solution)

In [1]:

import numpy as np

# Define array and scalar
x = np.array([1,2,3])
y = 5
z = x + y

print("x:", x)
print("y:", y)
print("Result:", z)



x: [1 2 3]
y: 5
Result: [6 7 8]


## Exercise 2 — Matrix + Vector Broadcasting (Solution)

In [2]:

a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([10,20,30])

c = a + b
print("a:\n", a)
print("b:\n", b)
print("Result:\n", c)

a:
 [[1 2 3]
 [4 5 6]]
b:
 [10 20 30]
Result:
 [[11 22 33]
 [14 25 36]]


## Exercise 3 — Row + Column Broadcasting (Solution)

In [3]:

col = np.array([[1],[2],[3]])
row = np.array([10,20,30,40])

result = col + row
print("col:\n", col)
print("row:\n", row)
print("Result:\n", result)



col:
 [[1]
 [2]
 [3]]
row:
 [10 20 30 40]
Result:
 [[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


## Exercise 4 — Broadcasting Error (Solution)

In [ ]:

a = np.ones((3,2))
b = np.ones((2,3))

print("a:\n", a)
print("b:\n", b)
# This will raise an error due to incompatible shapes
try:
    res = a + b
except ValueError as e:
    print("Broadcasting Error:", e)

#Solution - match the dimensions of either a or b by taking transpose.

a = np.ones((3,2)).T
print("a:\n", a)
print("b:\n", b)
res = a + b
print("Result:\n", res)



---
You have now seen scalar broadcasting, matrix + vector broadcasting, row + column broadcasting,  
and what happens when shapes do not align (broadcasting error).
