# Operational Software Technologies

## Topics

1. Libraries
2. Numpy  
3. Vectorisation  
  

**Credit:** Dr Ken Cameron  

### 1 Libraries (Introduction)

A library is a way of packaging code so that you can include it and make use of its functionality in your program. There are three kinds of library.

* The standard ones that come with Python and are always available to you.

* Those that have been additionally installed by you or and adminstrator, e.g. numpy.

* Those you create yourself.

Before you can use a library you need to tell Python that you intend to. To do that, you need to _import_ it. You only have to do it **once** per library.

In [1]:
#Import a complete library

import numpy

#Import a library but provide a different name you will use to reference it.

import numpy as np

#Import parts of a library

from numpy import array, sqrt

In [2]:
# If you use import or import as, you need to prefix the library functions and classes with the library name

print(numpy.sqrt(9.0))

print(np.sqrt(16.0))

# if you implement a specific function or class you can access it directly

print(sqrt(256.0))

3.0
4.0
16.0


Python uses namespaces to keep track of where things are defined. So far we've only looked at two.

The global namespace and the local namespace in a function.

When you declare a variable outside of a function, it's in the global namespace. That means you can use it in the global namespace. If you declare a variable in a function, then it only exists for the duration of a function call and is said to be in the local name space of the function.

In [3]:
x = 5 # this x is global

def a():
    print('inside a:', x) # the x here is global

def b():
    x = 8 # this x is local
    print('inside b:', x)

print(x)
a()
b()
print(x)

5
inside a: 5
inside b: 8
5


In [4]:
# We can tell Python that we'd like a variable in a function to always be global not local

x = 5

def c():
    global x
    x = 8
    print ('inside c:' , x)

print(x)
c()
print(x)

5
inside c: 8
8


In [5]:
x = 2

def outer_fn():
    x = 5

    def inner_fn( ):
        nonlocal x
        x = 8

    print('before inner_fn:', x)
    inner_fn()
    print('after inner_fn:', x)

outer_fn()
print('global:', x)

before inner_fn: 5
after inner_fn: 8
global: 2


Libraries also have a name space. By prefixing the name of the library, you are indicating that the function/class you want is part of that library.

**numpy.sin()**

is not the same function as

**math.sin()**

When you say **import ... from** you are asking Python to load the library and place its contents in the global namespace. While it might mean less typing, you can loose track of which version of a function or class you are using.

And for this reason you should never use * in an import.

** import * from numpy**

Is a really bad idea. If you did the same with **math**, you would not know which version of **sin()** you are using.

In [ ]:
# don't do this

from numpy import *

print(pi)

pi = 4

print(pi)

import numpy

print (numpy.pi)

### 2 Numpy

* Good for vectors, matrices and tensors.

* Use it in place of the **math** library. It replicates it and is better (faster.)

* Use numpy arrays in place of nested lists. **ndarray**


In [6]:
# We can create an array of multiple dimensions, where all data types are the same type.
import numpy as np

my_array = np.zeros([3,2], dtype=int)

print(my_array)

my_array.shape

[[0 0]
 [0 0]
 [0 0]]


(3, 2)

In [7]:
my_array = np.array([[1,2],[3,4]])

print(my_array)

print(my_array[0,1])

[[1 2]
 [3 4]]
2


In [8]:
my_other_array = my_array.reshape((1,4))

print(my_other_array)

my_other_array.shape

[[1 2 3 4]]


(1, 4)

In [9]:
my_other_array = my_array.reshape((4,1))

print(my_other_array)

my_other_array.shape

[[1]
 [2]
 [3]
 [4]]


(4, 1)

In [10]:
my_other_array[2,0] = 5

print(my_other_array)
print()
print(my_array) # we did n't take a copy, we are still refencing the initial array

[[1]
 [2]
 [5]
 [4]]

[[1 2]
 [5 4]]


In [11]:
# take a copy

copy_of_array = np.copy(my_array)

copy_of_array[0,0] = -5

print(my_array)
print(copy_of_array)

[[1 2]
 [5 4]]
[[-5  2]
 [ 5  4]]


They are a number of other array constructors in numpy

* empty() Does n't initialise the values.

* ones() Like zeros, but uses 1 not 0.

* identity() Mostly zeros with some ones.

You can apply perform element-wise operations on arrays using the standard operators.

* Use *, +, etc.

* The matrices have to have matching size.

There are also matrix operations.

* matmul()

* dot()

* mutiply(), just like using *

In [12]:
print(my_array + copy_of_array)
print()
print(my_array * copy_of_array)

[[-4  4]
 [10  8]]

[[-5  4]
 [25 16]]


In [13]:
print(np.dot(my_array,copy_of_array))

[[ 5 10]
 [-5 26]]


### 4. Vectorisation

Operations work on arrays not individual elements.

Let's look at adding 1 to each element of an array.

In [37]:
# You could do with with loops.

# Create 1D list
a  = [i for i in range(10)]
print(a)

# add 1 to each entry
for i in range(len(a)):
    a[i] += 1

print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [38]:
# again, but with list comprehension

b  = [i for i in range(10)]
print(b)

b = [v+1 for v in b]
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [39]:
# now use arrays

c = np.arange(10) # not used this before. Creates 1D array with range.
print(c)

# apply the operation to each element.
c += 1
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
