# Operational Software Technologies

## NumPy Broadcasting Worksheet

This worksheet introduces **NumPy broadcasting** through practical coding exercises.

Fill in the missing code (marked with `___`) to complete the examples. Use the slides for hints.

Dr Moody Alam

### Topics
>[Exercise 1 — Scalar Broadcasting](#scrollTo=71f09792)

>[Exercise 2 — Matrix + Vector Broadcasting](#scrollTo=b3997ede)

>[Exercise 3 — Row + Column Broadcasting](#scrollTo=d7c3dcbc)

>[Exercise 4 — Broadcasting Error](#scrollTo=1a0dd0a6)

## Exercise 1 — Scalar Broadcasting
Add a scalar to a NumPy array.

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])
y = 4   # choose a scalar
z = x + y   # add scalar to array

print(z)



[5 6 7]


## Exercise 2 — Matrix + Vector Broadcasting
Add a row vector to a 2D matrix.

In [4]:

A = np.array([[1,2,3],
              [4,5,6]])
b = np.array([10,20,30])

c = A + b   # broadcast row vector

print(c)


[[11 22 33]
 [14 25 36]]


## Exercise 3 — Row + Column Broadcasting
Perform an outer sum using a column and row vector.

In [5]:

col = np.array([[1],[2],[3]])
row = np.array([10,20,30,40])

result = col + row

print(result)


[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


## Exercise 4 — Broadcasting Error
Try adding incompatible shapes and observe the error.

In [6]:

a = np.ones((3,2))
b = np.ones((2,3))

print("a:\n", a)
print("b:\n", b)
# This will raise an error due to incompatible shapes
try:
    res = a + b
except ValueError as e:
    print("Broadcasting Error:", e)

# Match the dimension of a or b by taking a transponse
# To Do : Take the transpose
a + ___

# Add a+b to confirm that this works now.

a:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
b:
 [[1. 1. 1.]
 [1. 1. 1.]]
Broadcasting Error: operands could not be broadcast together with shapes (3,2) (2,3) 


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('float64'), dtype('<U46')) -> None


---
Congratulations! You have practiced scalar, matrix+vector, and row+column broadcasting, as well as seen what happens when shapes do not match.
